public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMuYk0mumUxsRJYlCp61Q74xWuHPwKoFhfDZPM84K5qPu7o7RzbaJe83496dcRInV0rbAovfYyCPtppraDtFJE8CAwEAAQ==
server:
  port: 8888
  tomcat:
    relaxed-query-chars: [ '[',']' ]
sff:
  algorithm:
    salt: 'mrbird'

spring:
  datasource:
    druid:
      name: druidDataSource
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      filter:
        config:
          enabled: true
      initial-size: 5
      max-active: 10
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 5
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 1
      pool-prepared-statements: true
      url: jdbc:mysql://127.0.0.1:3306/rbac?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: WXlOncN1J7b6ZTTRWhP3C/zqiyeEC2NWQej6Eu91Odw0L3a/WACxxccuef7WUNFBazRO9bF+ddBOpB2Otq1Bjw==
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key};
  mail:
    host: smtp.qq.com   #阿里云发送服务器地址
#    port: 25           #端口号
    username: 237387963@qq.com    #发送人地址
    password: qpijaqllnmwxbiie  #密码

mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken:
    executor:
      appname: abnormal-billing-notification-job
      address:
      ip:
      port: 0
      logpath: ./data/applogs/xxl-job/jobhandler
      logretentiondays: 30

